# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_MkqVJJXbsBqytVr0WXcenEdzRX_zWj
"""

import numpy
n=input() #no of input arrays
a=numpy.array([input().split() for i in range(int(n))],int) #input arrays
b=numpy.transpose(a) #transpose of the input arrays
c=b.flatten() #flatten array of the transpose array
print(c)